name: CI

on: [push, pull_request]

env:
  VERBOSE: 1

jobs:
  gcc13-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: gcc-13
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  gcc12-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  gcc11-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: gcc-11
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  gcc10-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  gcc9-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  clang15-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: clang-15
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  clang14-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: clang-14
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  clang13-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: clang-13
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  clang12-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: clang-12
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh

  clang11-x86_64:
    runs-on: ubuntu-latest
    env:
      CC: clang-11
      TARGET: x86_64
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: ci/install-dependencies.sh
    - name: build check
      run: ci/run-build-and-tests.sh
